version: "3"
services:
    my_pets_store:
        container_name: my_pets_store
        build:
            context: .
        command: ["python", "-u", "./main.py"]
        restart: always
        ports:
            - "8006:8006"
        networks:
          - myTestNetwork


networks:
  myTestNetwork:
    driver: bridge