version: "3"
services:
    my_pets_store:
        container_name: my_pets_store
        build:
            context: .
        command: ["python", "-u", "./main.py"]
#        healthcheck:
#            test: curl --http0.9 localhost:${health_check_port}
#            interval: 5s
#            timeout: 5s
#            retries: 3
        restart: always
        ports:
            - "8004:8004"
        networks:
          - myTestNetwork


networks:
  myTestNetwork:
    driver: bridge
